/* 
 * (C) Copyright 2015 by MSDK Development Team
 *
 * This software is dual-licensed under either
 *
 * (a) the terms of the GNU Lesser General Public License version 2.1
 * as published by the Free Software Foundation
 *
 * or (per the licensee's choosing)
 *
 * (b) the terms of the Eclipse Public License v1.0 as published by
 * the Eclipse Foundation.
 */

package io.github.msdk.datamodel;

import io.github.msdk.datamodel.rawdata.DataPointList;

/**
 * Tests tools for MSDK data model
 */
public class DataModelTestTools {

    /**
     * Generates a DataPointList pre-filled with a given number of data points
     * (count).
     * 
     * To assure that the lists generated by this method are not all the same,
     * the data points have m/z values of
     * 
     * <pre>
     * count / count ( = 1.0)
     * ...
     * count / 3.0
     * count / 2.0
     * count / 1.0
     * </pre>
     * 
     * Their intensity is always equal to m/z * 2.
     */
    public static DataPointList generateDataPoints(int count) {

        final DataPointList list = MSDKObjectBuilder.getDataPointList(count);
        final double mzValues[] = list.getMzBuffer();
        final float intensityValues[] = list.getIntensityBuffer();

        for (int i = 0; i < count; i++) {
            mzValues[i] = (double) count / (double) (count - i);
            intensityValues[i] = (float) mzValues[i] * 2;
        }

        return list;
    }

}
